name: Debug compile Chawrt Firmware

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target platform'
        required: true
        default: 'x86'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-dev python3-setuptools python3-pip rsync unzip zlib1g-dev file wget
        sudo apt install python2.7 || sudo apt install python-is-python3 qemu-utils
        
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: true
        repository: liudf0716/chawrt
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .config based on input
      run: |
        cp ${{ github.event.inputs.target }}.config .config

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    
    - name: Download files
      run: |
        make defconfig
        make -j4 download

    - name: Compile firmware
      run: |
        make -j$(nproc) || make -j1 V=s
        
    - name: Copy combined files
      run: |
        mkdir output
        if [[ "${{ github.event.inputs.target }}" == "x86" ]]; then
          cp bin/targets/${{ github.event.inputs.target }}/64/*squashfs-combined.* output/
        elif [[ "${{ github.event.inputs.target }}" == "panther" ]]; then
          cp bin/targets/rockchip/rk35xx/*.gz output/
        fi

    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: chawrt-${{ github.event.inputs.target }}-firmware
        path: output/
        retention-days: 1
